import pandas as pd
import numpy as np

# Part D: AI-Augmented Task
"""
Documented prompt sent to AI:
You are an expert Python data engineer specializing in production-quality data cleaning pipelines.

Write a Python function called `clean_dataframe` that accepts a messy Pandas DataFrame and returns a tuple of `(cleaned_df, summary_dict)`. The function must handle all of the following in sequence:

**Hidden missing value detection and replacement:**
- Detect and replace string variants `'N/A'`, `'n/a'`, `''`, `'null'`, `'None'`, `'none'`, `'nan'`, and any leading/trailing whitespace-only strings with `np.nan` across all columns before any type inference

**Type inference and conversion for object columns:**
- Attempt numeric conversion using `pd.to_numeric` with `errors='coerce'`; if conversion succeeds for a meaningful proportion of non-null values, apply it
- For columns that remain object type after numeric attempt, try datetime parsing using `pd.to_datetime` with `errors='coerce'` and `infer_datetime_format=True`; apply if conversion yields a meaningful proportion of valid dates
- Leave columns as object type if neither numeric nor datetime conversion succeeds

**Text column standardization (applied to all remaining object/string columns):**
- Strip leading and trailing whitespace
- Convert to lowercase

**Duplicate row removal:**
- Drop exact duplicate rows, keeping the first occurrence

**Summary reporting — the returned `summary_dict` must include:**
- `missing_values_replaced`: count of cells where hidden missing values were replaced per column
- `type_conversions`: which columns were converted and to what dtype
- `text_standardized`: list of columns that had text standardization applied
- `duplicates_removed`: integer count of duplicate rows dropped
- `final_shape`: tuple of the cleaned DataFrame's shape

**Code quality requirements:**
- No in-place mutation of the input DataFrame; operate on a copy
- All steps must be wrapped in try/except with informative error messages
- Include a docstring describing parameters, return values, and behavior
- Include a `if __name__ == "__main__":` block with a realistic messy test DataFrame that exercises all cleaning steps, printing the summary and displaying `cleaned_df.dtypes`
"""

def ai_generated_cleaner(df: pd.DataFrame) -> tuple[pd.DataFrame, dict]:
    summary = {
        'initial_rows': len(df),
        'initial_cols': df.shape[1],
        'missing_values_replaced': 0,
        'types_converted': [],
        'duplicates_removed': 0
    }
    
    # 1. Replace hidden missing values
    hidden_missing = ['N/A', 'n/a', '', ' ', 'null', 'None', 'none']
    df_clean = df.replace(hidden_missing, np.nan)
    summary['missing_values_replaced'] = int(df_clean.isna().sum().sum() - df.isna().sum().sum())
    
    # 2. Standardize text & Convert appropriate types
    for col in df_clean.columns:
        if df_clean[col].dtype == 'object':
            # Try numeric
            try:
                # Remove commas just in case it's a number like 1,000
                test_col = df_clean[col].astype(str).str.replace(',', '')
                converted = pd.to_numeric(test_col, errors='raise')
                df_clean[col] = converted
                summary['types_converted'].append(f"{col} -> Numeric")
                continue
            except (ValueError, TypeError):
                pass
            
            # Try datetime
            try:
                # Let pandas infer mixed date formats
                converted = pd.to_datetime(df_clean[col], errors='raise')
                df_clean[col] = converted
                summary['types_converted'].append(f"{col} -> Datetime")
                continue
            except (ValueError, TypeError, pd.errors.ParserError):
                pass
            
            # If neither, standardize string natively
            # Make sure to handle floats/NaN properly if performing string operation
            df_clean[col] = df_clean[col].astype(str).str.strip().str.lower()
            # replace literal nan strings generated by astype back to np.nan
            df_clean[col] = df_clean[col].replace('nan', np.nan)

    # 3. Remove duplicates
    initial_dups = len(df_clean)
    df_clean = df_clean.drop_duplicates()
    summary['duplicates_removed'] = initial_dups - len(df_clean)
    summary['final_rows'] = len(df_clean)
    
    return df_clean, summary

if __name__ == '__main__':
    messy_test = pd.DataFrame({
        'price': ['1,000', '2,500', 'N/A', 'None'], # Mixed commas and hidden na
        'date': ['12/05/2021', '2021-05-13', '', 'Jan 5th 2022'], # Complex date mix
        'name': ['  Alice ', 'BOB', ' bob', 'Charlie'], # Messy string and duplicate target
        'category': ['X', 'X', 'X', 'Y']
    })
    
    # Appending true duplicate row
    messy_test = pd.concat([messy_test, messy_test.iloc[[1]]], ignore_index=True)
    
    clean_out, sum_out = ai_generated_cleaner(messy_test)
    print("AI Cleaner Summary Report:")
    print(sum_out)
    print("\nCleaned DF Frame Output:")
    print(clean_out.dtypes)
    print(clean_out)

"""
Critical Evaluation (200 words):
The AI-generated cleaner robustly handles mixed data typing by leveraging strict exception handling blocks `errors='raise'` sequentially, falling back to string coercion logically. It accounts for mixed date formats implicitly because `pd.to_datetime()` parses diverse variants by default context scopes. 

However, edge cases specifically regarding entirely NaN columns will technically process as Float64 without breaking, but there is no explicitly written fill-strategy logic for imputation (It purely detects/replaces, rather than fills via median/mean mechanisms based on schemas).

Performance-wise, `pd.to_datetime()` processing completely blindly `errors='raise'` across entirely Object columns on a 1 Million row dataset scales incredibly poorly. Attempting to force parse strings constantly and relying heavily on error handling recursion is computational overhead that will dramatically slow down execution. 

To improve:
1. I would utilize `errors='coerce'` uniformly and pre-validate string columns via `.str.contains(r'\d')` regex filters prior to attempting massive date conversions. 
2. Add dictionary inputs to manually supply fill strategies (mean, median) per column target post-cleaning. The lack of structured statistical fills makes missing value replacement effectively useless for downstream machine learning.
"""
